config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :comments, only: [:create]

  resources :instagrams do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  root 'instagrams#index'
  delete 'comments/:id' => 'comments#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :instagram
end

app/models/instagram.rb
class Instagram < ApplicationRecord

    belongs_to :user

    mount_uploader :image, ImageUploader

    has_many :comments, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :instagram
  belongs_to :user

  validates_uniqueness_of :instagram_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :instagrams, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  has_many :liked_instagrams, through: :likes, source: :instagram

  def already_liked?(instagram)
    self.likes.exists?(instagram_id: instagram.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters

        devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])

        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile,:image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
    instagram = Instagram.find(params[:instagram_id])
      comment = instagram.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end

    def destroy
      comment = Comment.find(params[:id])
      comment.destroy
      redirect_to action: :index
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
    end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
    
end

app/controllers/instagrams_controller.rb
class InstagramsController < ApplicationController
  before_action :authenticate_user!

  def index

    if params[:search] == nil
      @instagrams= Instagram.all
    elsif params[:search] == ''
      @instagrams= Instagram.all
    else
      @instagrams = Instagram.where("body LIKE ? ",'%' + params[:search] + '%')
    end
    
  end

  def new
      @instagram = Instagram.new
  end
  
  def create
    instagram = Instagram.new(instagram_params)
    instagram.user_id = current_user.id
      if instagram.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end
  
  def show
    @instagram = Instagram.find(params[:id])

    @comments = @instagram.comments
    @comment = Comment.new

  end

  def edit
    @instagram = Instagram.find(params[:id])
  end

  def update
    instagram = Instagram.find(params[:id])
    if instagram.update(instagram_params)
      redirect_to :action => "show", :id => instagram.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    instagram = Instagram.find(params[:id])
    instagram.destroy
    redirect_to action: :index
  end

  private
  def instagram_params
      params.require(:instagram).permit(:body,:image)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(instagram_id: params[:istagram_id]) 
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(instagram_id: params[:instagram_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/instagrams_helper.rb
module InstagramsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
アイコン
<%= link_to "GeekInstagramにログイン", new_user_session_path %>
<%= link_to "新しくアカウントを作る", new_user_registration_path %>

app/views/hello/link.html.erb
My name is naoya.
<%= link_to 'トップページ', :controller => "hello", :action => "index" %>
<%= link_to '一覧表示', :controller => "instagrams", :action => "index" %>

app/views/instagrams/edit.html.erb
<%= form_for @instagram do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
<% end %>

app/views/instagrams/index.html.erb
<h3>投稿一覧</h3>

<div class="container">
  <div class="row">
    <% @instagrams.each do |t| %>
      <div class="col-sm-3">
      <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.body %>

      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to instagram_like_path(id: t.id, instagram_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= link_to instagram_likes_path(id: t.id, instagram_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>

      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            ?
          </button>          
          <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <%= link_to "詳細", instagram_path(t.id), class:'dropdown-item' %>
            <% if user_signed_in? && current_user.id == t.user_id %>  
              <%= link_to "編集", edit_instagram_path(t.id), class:'dropdown-item' %>
              <%= button_to "削除", instagram_path(t.id), class:'dropdown-item', method: :delete %>
            <% end %> 
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/instagrams/new.html.erb
<div class="new-all">
  <h3>新規投稿</h3>
  <%= form_for @instagram do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :body, :size => 140 %>
    </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit "共有する" %>
  <% end %>
  <%= link_to "投稿一覧に戻る", instagrams_path %>
</div>

app/views/instagrams/show.html.erb
<h3>投稿詳細</h3>
<div class="instagram">
  <p><a href="/users/<%= @instagram.user.id %>"><%= @instagram.user.name %></a></p>
  <p><%= image_tag @instagram.image_url, size: "250x200" if @instagram.image? %></p>
  <p><%= @instagram.body %></p>

  <% if user_signed_in? %>
    <% if current_user.already_liked?(@instagram) %>
      <%= link_to instagram_like_path(@instagram), method: :delete do %>
        <i class="fas fa-heart"></i><%= @instagram.likes.count %>
      <% end %>
    <% else %>
      <%= link_to instagram_likes_path(@instagram), method: :post do %>
        <i class="far fa-heart"></i><%= @instagram.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <i class="far fa-heart"></i><%= @instagram.likes.count %>
  <% end %>

  <h2>いいねしたユーザー</h2>
  <% @instagram.liked_users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>

  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
        <%= button_to "削除", comment_path(c.id), class:'dropdown-item', method: :delete %>
      </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@instagram, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit",  class:'btn btn-primary' do %>
          コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>

  <% if user_signed_in? && current_user.id == @instagram.user_id %>  
    <%= link_to "編集する", edit_instagram_path %>
    <%= button_to "削除する", instagram_path, method: :delete %>
  <% end %> 
</div>

<%= link_to "投稿一覧に戻る", instagrams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekInstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>GeekInstagram</h1>
      <div class="header-list">
      <ul>
      <% if user_signed_in? %>
        <li>
        <%= form_tag({controller:"instagrams",action:"index"}, method: :get) do %>
          <%= text_field_tag :search %>
          <%= submit_tag '検索する'  %>
        <% end %>
        </li>
        <li><%= link_to "ホーム", instagrams_path %></li>
        <li><%= link_to "新規投稿",new_instagram_path %></li>
        <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
      <% end %>
      </ul>
      </div>
    </header>
  
    <main>
      <%= yield %>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
    
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p><%= image_tag @user.image_url, size: "100x100" if @user.image? %>
<p>名前 : <%= @user.name %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.instagrams.each do |t| %>
  <%= t.user.name %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.body %>
<% end %>

<%= link_to "投稿一覧に戻る", instagrams_path %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>